
export enum VoiceName {
  Achernar = 'Achernar',
  Achird = 'Achird',
  Algenib = 'Algenib',
  Algieba = 'Algieba',
  Alnilam = 'Alnilam',
  Aoede = 'Aoede',
  Autonoe = 'Autonoe',
  Callirrhoe = 'Callirrhoe',
  Charon = 'Charon',
  Despina = 'Despina',
  Enceladus = 'Enceladus',
  Erinome = 'Erinome',
  Fenrir = 'Fenrir',
  Gacrux = 'Gacrux',
  Iapetus = 'Iapetus',
  Kore = 'Kore',
  Laomedeia = 'Laomedeia',
  Leda = 'Leda',
  Orus = 'Orus',
  Puck = 'Puck',
  Pulcherrima = 'Pulcherrima',
  Rasalgethi = 'Rasalgethi',
  Sadachbia = 'Sadachbia',
  Sadaltager = 'Sadaltager',
  Schedar = 'Schedar',
  Sulafat = 'Sulafat',
  Umbriel = 'Umbriel',
  Vindemiatrix = 'Vindemiatrix',
  Zephyr = 'Zephyr',
  Zubenelgenubi = 'Zubenelgenubi',
}

export const VOICE_LABELS: Record<VoiceName, string> = {
  [VoiceName.Achernar]: 'Achernar (Female, Normal)',
  [VoiceName.Achird]: 'Achird (Male, Normal)',
  [VoiceName.Algenib]: 'Algenib (Male, Normal)',
  [VoiceName.Algieba]: 'Algieba (Male, Normal)',
  [VoiceName.Alnilam]: 'Alnilam (Male, Normal)',
  [VoiceName.Aoede]: 'Aoede (Female, Normal)',
  [VoiceName.Autonoe]: 'Autonoe (Female, Normal)',
  [VoiceName.Callirrhoe]: 'Callirrhoe (Female, Normal)',
  [VoiceName.Charon]: 'Charon (Male, Normal)',
  [VoiceName.Despina]: 'Despina (Female, Normal)',
  [VoiceName.Enceladus]: 'Enceladus (Male, Normal)',
  [VoiceName.Erinome]: 'Erinome (Female, Normal)',
  [VoiceName.Fenrir]: 'Fenrir (Male, Normal)',
  [VoiceName.Gacrux]: 'Gacrux (Female, Normal)',
  [VoiceName.Iapetus]: 'Iapetus (Male, Normal)',
  [VoiceName.Kore]: 'Kore (Female, Normal)',
  [VoiceName.Laomedeia]: 'Laomedeia (Female, Normal)',
  [VoiceName.Leda]: 'Leda (Female, Normal)',
  [VoiceName.Orus]: 'Orus (Male, Normal)',
  [VoiceName.Puck]: 'Puck (Female, Normal)',
  [VoiceName.Pulcherrima]: 'Pulcherrima (Female, Normal)',
  [VoiceName.Rasalgethi]: 'Rasalgethi (Male, Normal)',
  [VoiceName.Sadachbia]: 'Sadachbia (Male, Normal)',
  [VoiceName.Sadaltager]: 'Sadaltager (Male, Normal)',
  [VoiceName.Schedar]: 'Schedar (Male, Normal)',
  [VoiceName.Sulafat]: 'Sulafat (Female, Normal)',
  [VoiceName.Umbriel]: 'Umbriel (Male, Normal)',
  [VoiceName.Vindemiatrix]: 'Vindemiatrix (Female, Normal)',
  [VoiceName.Zephyr]: 'Zephyr (Female, Normal)',
  [VoiceName.Zubenelgenubi]: 'Zubenelgenubi (Male, Normal)',
};

export interface TTSState {
  isLoading: boolean;
  isPlaying: boolean;
  error: string | null;
  audioBuffer: AudioBuffer | null;
}
